ALTER TABLE "guild_settings"
ADD COLUMN IF NOT EXISTS "server_name" TEXT,
ADD COLUMN IF NOT EXISTS "timezone" TEXT NOT NULL DEFAULT 'Asia/Singapore',
ADD COLUMN IF NOT EXISTS "region" TEXT,
ADD COLUMN IF NOT EXISTS "language" TEXT NOT NULL DEFAULT 'en';
